#!/bin/sh

##########################################################
##                                                      ##
## This will automate the environment setup and running ##
## of Heritrix following a successful build.  You 	##
## should only need to modify JAVA_HOME to make it work ##
##							##
##########################################################

if [ ! $CRAWL_HOME ]; then
	echo ""
	echo "  Before running this script you must set"
	echo "  the environemnt variable CRAWL_HOME"
	echo ""
	exit
fi

## the following block reads common (shared) environment
## variables from the configuration file

# set field seperator to split on newlines
IFS='
'
for line in `cat $CRAWL_HOME/environment.txt`
do
	notcomment=${line##\#*}
	if [ $notcomment ]; then
		export $line
	fi
done

## make sure we got what we needed from the
## env var file
if [ ! $JAVA_HOME ]; then
        echo ""
	echo "  Error: JAVA_HOME is not set.  Set this environment variable"
	echo "  manually, or create an appropriate entry in 'environment.txt'."
	echo "  See the documentation for more information on setting up your"
	echo "  crawl environment"
        echo ""
        exit
fi


## other environment variables
export RUN_LOC="$CRAWL_HOME/RunThis"
export LIB_DIR="$RUN_LOC/lib"

export CRAWL_CP="$RUN_LOC/crawlerclasses.jar:$LIB_DIR/crawlerclasses.jar:$LIB_DIR/commons-httpclient.jar:$LIB_DIR/dnsjava.jar:$LIB_DIR/stataclasses.jar:$LIB_DIR/junit.jar:$LIB_DIR/commons-logging.jar:$LIB_DIR/itext.jar:$LIB_DIR/jasper-compiler.jar:$LIB_DIR/jasper-runtime.jar:$LIB_DIR/javaswf.jar:$LIB_DIR/javax.servlet.jar:$LIB_DIR/jcert.jar:$LIB_DIR/jmxri.jar:$LIB_DIR/jmxtools.jar:$LIB_DIR/jnet.jar:$LIB_DIR/jsse.jar:$LIB_DIR/org.mortbay.jetty.jar:$LIB_DIR/org.mortbay.jmx.jar:$LIB_DIR/poi.jar:$LIB_DIR/xercesImpl.jar:$LIB_DIR/xml-apis.jar:$LIB_DIR/xmlParserAPIs.jar"

## check arguments passed
if [ ! $1 ] || [ $1 = -no-wui ] && [ ! $2 ]; then

	echo ""
	echo "  usage: starttcrawl.sh [-no-wui] <order.xml>"
	echo ""
	exit
fi

if [ $1 = -no-wui ]; then
	args="$1 $2"
else
	args="$1"
fi

# move arc files generated by old runs (if applicable)
mkdir oldarcs > /dev/null 2>&1
mv arcs/* oldarcs > /dev/null 2>&1

## run this sucker
if [ "$1"="-no-wui" ]; then
	echo "Running the crawler with no gui"
	echo ""
	$JAVA_HOME/bin/java -cp "$CRAWL_CP" org.archive.crawler.Heritrix -no-wui $args

else
	echo "To start the crawler connect via http to port 8080 and press start"
	echo ""
	$JAVA_HOME/bin/java -cp "$CRAWL_CP" org.archive.crawler.Heritrix $args
fi

exit
